const express = require('express');
const path = require('path');
const Groq = require('groq-sdk');
const Razorpay = require('razorpay');
const crypto = require('crypto');

const app = express();
const groq = new Groq({ apiKey: process.env.GROQ_API_KEY });

const razorpay = new Razorpay({
  key_id: process.env.RAZORPAY_KEY_ID,
  key_secret: process.env.RAZORPAY_KEY_SECRET,
});

app.use(express.json());
app.use(express.static(path.join(__dirname)));

// ─── Page Routes ────────────────────────────────────────────────────────────
const pageStyle = `
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', sans-serif; background: #0d1117; color: #e6edf3; min-height: 100vh; }
    .container { max-width: 760px; margin: 0 auto; padding: 60px 24px; }
    h1 { font-size: 2rem; color: #00d4aa; margin-bottom: 8px; }
    .subtitle { color: #8b949e; margin-bottom: 40px; font-size: 0.95rem; }
    h2 { font-size: 1.1rem; color: #c9d1d9; margin: 28px 0 10px; }
    p, li { color: #8b949e; line-height: 1.7; margin-bottom: 10px; }
    ul { padding-left: 20px; }
    a { color: #00d4aa; text-decoration: none; }
    a:hover { text-decoration: underline; }
    .back { display: inline-block; margin-bottom: 40px; font-size: 0.9rem; }
    .card { background: #161b22; border: 1px solid #30363d; border-radius: 12px; padding: 32px; margin-top: 8px; }
    .badge { display: inline-block; background: #00d4aa22; color: #00d4aa; border: 1px solid #00d4aa44;
             font-size: 0.75rem; padding: 3px 10px; border-radius: 20px; margin-bottom: 20px; }
  </style>
`;

app.get('/privacy', (req, res) => res.send(`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Privacy Policy - PromptKit India</title>${pageStyle}</head>
  <body><div class="container">
    <a href="/" class="back">← Back to Home</a>
    <span class="badge">Legal</span>
    <h1>Privacy Policy</h1>
    <p class="subtitle">Last updated: June 2026</p>
    <div class="card">
      <h2>What We Collect</h2>
      <p>We collect only the information you provide — business type, city, and language preference — to generate AI prompts. We do not store this data on our servers after your session ends.</p>
      <h2>API Usage</h2>
      <p>Your inputs are sent to Groq's API to generate content. Please refer to <a href="https://groq.com/privacy" target="_blank">Groq's Privacy Policy</a> for how they handle data.</p>
      <h2>No Account Required</h2>
      <p>PromptKit India does not require sign-up. We do not collect email addresses, phone numbers, or payment information.</p>
      <h2>Cookies</h2>
      <p>We do not use tracking cookies or analytics that identify you personally.</p>
      <h2>Contact</h2>
      <p>Questions? Email us at <a href="mailto:hello@promptkitindia.com">hello@promptkitindia.com</a></p>
    </div>
  </div></body></html>`));

app.get('/terms', (req, res) => res.send(`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Terms of Service - PromptKit India</title>${pageStyle}</head>
  <body><div class="container">
    <a href="/" class="back">← Back to Home</a>
    <span class="badge">Legal</span>
    <h1>Terms of Service</h1>
    <p class="subtitle">Last updated: June 2026</p>
    <div class="card">
      <h2>Use of Service</h2>
      <p>PromptKit India provides AI-generated marketing content for informational and business use. You may use, edit, and publish the generated content freely for your business.</p>
      <h2>Limitations</h2>
      <ul>
        <li>Do not use this tool to generate spam, misleading, or harmful content.</li>
        <li>AI-generated content should be reviewed before publishing — we are not responsible for errors.</li>
        <li>Service availability is not guaranteed; we may update or discontinue features at any time.</li>
      </ul>
      <h2>Intellectual Property</h2>
      <p>The generated content belongs to you. PromptKit India's design, code, and branding remain our property.</p>
      <h2>Disclaimer</h2>
      <p>Content is generated by AI and may not always be accurate or suitable. Use your judgment before publishing.</p>
    </div>
  </div></body></html>`));

app.get('/contact', (req, res) => res.send(`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Contact - PromptKit India</title>${pageStyle}</head>
  <body><div class="container">
    <a href="/" class="back">← Back to Home</a>
    <span class="badge">Support</span>
    <h1>Contact Us</h1>
    <p class="subtitle">We'd love to hear from you</p>
    <div class="card">
      <h2>📧 Email</h2>
      <p><a href="mailto:hello@promptkitindia.com">hello@promptkitindia.com</a></p>
      <h2>🕐 Response Time</h2>
      <p>We typically respond within 24–48 hours on working days.</p>
      <h2>💡 Feature Requests</h2>
      <p>Have an idea to improve PromptKit India? We welcome suggestions — write to us with "Feature Request" in the subject line.</p>
      <h2>🐛 Bug Reports</h2>
      <p>Found something broken? Describe the issue and we'll fix it quickly.</p>
    </div>
  </div></body></html>`));

app.get('/about', (req, res) => res.send(`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>About - PromptKit India</title>${pageStyle}</head>
  <body><div class="container">
    <a href="/" class="back">← Back to Home</a>
    <span class="badge">About</span>
    <h1>About PromptKit India</h1>
    <p class="subtitle">AI-powered marketing content for Indian small businesses</p>
    <div class="card">
      <h2>Our Mission</h2>
      <p>Millions of small businesses in India struggle with marketing — not because they lack great products, but because writing captions, messages, and ads in the right tone takes time and skill. PromptKit India solves that in seconds.</p>
      <h2>What We Do</h2>
      <p>Enter your business type and city, and get 5 ready-to-use marketing pieces — Instagram captions, WhatsApp messages, Google posts, ad copy, and more. In Hindi or English. Free.</p>
      <h2>Built For India</h2>
      <p>Our AI understands Indian audiences, local festivals, regional context, and the way real customers talk. No generic global templates — everything feels local.</p>
      <h2>🚀 Free Forever</h2>
      <p>No signup. No credit card. Just results.</p>
    </div>
  </div></body></html>`));

// ─── Razorpay: Create Order ──────────────────────────────────────────────────
app.post('/api/create-order', async (req, res) => {
  try {
    const { amount } = req.body;

    // Valid amounts sirf: 19900 (₹199) ya 44900 (₹449)
    const validAmounts = [19900, 44900];
    if (!validAmounts.includes(amount)) {
      return res.status(400).json({ error: 'Invalid amount' });
    }

    const order = await razorpay.orders.create({
      amount,
      currency: 'INR',
      receipt: `receipt_${Date.now()}`,
    });
    res.json(order);
  } catch (err) {
    console.error('Razorpay order error:', err.message);
    res.status(500).json({ error: 'Order create nahi hua. Dobara try karo.' });
  }
});

// ─── Razorpay: Verify Payment ────────────────────────────────────────────────
app.post('/api/verify-payment', (req, res) => {
  try {
    const { razorpay_order_id, razorpay_payment_id, razorpay_signature } = req.body;

    const sign = razorpay_order_id + '|' + razorpay_payment_id;
    const expected = crypto
      .createHmac('sha256', process.env.RAZORPAY_KEY_SECRET)
      .update(sign)
      .digest('hex');

    if (expected === razorpay_signature) {
      // Payment verified — frontend ko Pro unlock signal bhejo
      res.json({ success: true, payment_id: razorpay_payment_id });
    } else {
      res.status(400).json({ success: false, error: 'Invalid payment signature' });
    }
  } catch (err) {
    console.error('Verify error:', err.message);
    res.status(500).json({ success: false, error: 'Verification failed' });
  }
});

// ─── Generate Prompts ────────────────────────────────────────────────────────
app.post('/api/generate', async (req, res) => {
  try {
    const { biz, city, lang, prob, category, outputTypes } = req.body;

    if (!biz) return res.status(400).json({ error: 'Business type required' });

    const types = (outputTypes && outputTypes.length > 0)
      ? outputTypes
      : ['Instagram Caption', 'WhatsApp Message', 'Google Business Post', 'Ad Copy', 'Sales Pitch'];

    const cityStr = city ? ` in ${city}` : '';

    const systemPrompt = `You are an expert Indian small business marketing AI. You generate ready-to-use content for local Indian businesses. Always write content that is practical, culturally relevant, and sounds natural for Indian audiences. Return ONLY valid JSON, no markdown, no extra text.`;

    const userPrompt = `Generate business content for the following:
- Business: ${biz}${cityStr}
- Language: ${lang}
- Biggest challenge: ${prob}
- Category: ${category}
- Content types needed: ${types.join(', ')}

Generate exactly ${types.length} pieces of content — one for each content type.

Return a JSON object in this exact format:
{
  "title": "Content for [business] ${cityStr}",
  "prompts": [
    {
      "output_type": "<exact content type from the list>",
      "use_case": "<short descriptive name, e.g. 'Festival Offer Post'>",
      "prompt": "<the actual ready-to-use content, 3-6 sentences, in ${lang}>",
      "tip": "<one practical tip for using this content>"
    }
  ]
}

Rules:
- prompt must be actual usable content (post text, message text), NOT a meta-prompt
- Include relevant emojis for social content
- Make content specific to ${biz}${cityStr}
- For WhatsApp: keep it conversational and short
- For Instagram: include hashtags at the end
- For Google Post: professional tone, mention location
- For Ad Copy: strong hook + clear call to action
- For SEO Blog: start with an engaging intro paragraph`;

    const completion = await groq.chat.completions.create({
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt }
      ],
      model: 'llama-3.3-70b-versatile',
      temperature: 0.8,
      max_tokens: 2000,
    });

    const raw = completion.choices[0]?.message?.content || '';
    const cleaned = raw.replace(/```json|```/g, '').trim();

    let parsed;
    try {
      parsed = JSON.parse(cleaned);
    } catch (e) {
      console.error('JSON parse failed:', cleaned.substring(0, 300));
      return res.status(500).json({ error: 'AI response parse error. Please try again.' });
    }

    if (!parsed.prompts || !Array.isArray(parsed.prompts)) {
      return res.status(500).json({ error: 'Invalid AI response format. Please try again.' });
    }

    res.json(parsed);

  } catch (err) {
    console.error('Generate error:', err.message);
    res.status(500).json({ error: 'Server error. Please try again.' });
  }
});

// ─── AI Edit Route ───────────────────────────────────────────────────────────
app.post('/api/edit', async (req, res) => {
  const { prompt, action } = req.body;

  if (!prompt || !action) {
    return res.status(400).json({ error: 'prompt aur action dono chahiye' });
  }

  const instructions = {
    improve:      'Improve this marketing content — make it more compelling, specific, and effective. Keep the same language.',
    shorter:      'Make this content shorter and more concise. Remove filler, keep the core message strong.',
    hindi:        'Rewrite this content completely in Hindi language only.',
    funny:        'Rewrite this content with a fun, light-hearted, and witty tone. Keep it appropriate for business.',
    professional: 'Rewrite this content in a formal, polished, professional tone suitable for corporate clients.',
  };

  const instruction = instructions[action];
  if (!instruction) {
    return res.status(400).json({ error: 'Invalid action' });
  }

  try {
    const completion = await groq.chat.completions.create({
      messages: [
        {
          role: 'system',
          content: 'You are an expert marketing copywriter for Indian small businesses. Return ONLY the rewritten content text — no explanation, no quotes, no preamble.',
        },
        {
          role: 'user',
          content: `${instruction}\n\nOriginal content:\n${prompt}`,
        },
      ],
      model: 'llama-3.1-8b-instant',
      max_tokens: 500,
      temperature: 0.8,
    });

    const result = completion.choices[0]?.message?.content?.trim();
    if (!result) throw new Error('Empty response from Groq');

    res.json({ result });

  } catch (err) {
    console.error('Edit error:', err.message);
    res.status(500).json({ error: 'Edit nahi hua. Dobara try karo.' });
  }
});

// ─── Start Server ────────────────────────────────────────────────────────────
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`PromptKit running on port ${PORT}`));
